API_staff/candidates/urls.py
from django.urls import path
from . import views


app_name = "candidates"

urlpatterns = [
    path("", views.CandidateList.as_view()),
    path("create/", views.CandidateCreate.as_view(), name="create"),
    path("delete/<int:pk>/", views.CandidateDelete.as_view(), name="delete"),
    path("<int:pk>/", views.CandidateDetail.as_view(), name="detail"),
]

API_staff/conf/urls.py
from django.contrib import admin
from django.urls import path, include

from candidates.views import redirect_home

urlpatterns = [
    path('', redirect_home),
    path('admin/', admin.site.urls),
    path('candidates/', include('candidates.urls', namespace="candidates")),

]

hospital_staff_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staff.urls', namespace='staff')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views


app_name = 'staff'

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.reset, name='reset'),
]

API_staff/candidates/models.py
from django.db import models


class Candidate(models.Model):
    GENDER_CHOICES = [
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
    ]

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    university = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms


class SearchForm(forms.Form):

    GENDER_CHOICES = (
        ('', 'Select Gender'),
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
    )

    search = forms.CharField(required=False)
    city = forms.CharField(required=False)
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.Select, required=False)
    age_more_than = forms.IntegerField(required=False)
    age_less_than = forms.IntegerField(required=False)

API_staff/candidates/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Candidate
from rest_framework import generics
from .serializers import CandidateSerializer


def redirect_home(request):
    return redirect('candidates/')


class CandidateList(generics.ListAPIView):
    queryset = Candidate.objects.all()
    serializer_class = CandidateSerializer


class CandidateDetail(generics.RetrieveAPIView):
    queryset = Candidate.objects.all()
    serializer_class = CandidateSerializer


class CandidateCreate(generics.CreateAPIView):
    queryset = Candidate.objects.all()
    serializer_class = CandidateSerializer


class CandidateDelete(generics.RetrieveDestroyAPIView):
    queryset = Candidate.objects.all()
    serializer_class = CandidateSerializer

staff/views.py
from django.shortcuts import render
import requests
from .forms import SearchForm

def index(request):

    url = "http://127.0.0.1:8080/candidates/"
    form = SearchForm(request.POST or None)

    if request.method == "GET":
        response = requests.get(url).json()
        return render(request, 'candidates/index.html', {"response": response, "form": form})
    
    if request.method == "POST" and form.is_valid():
        response = requests.get(url).json()
        key = form.cleaned_data['search']
        city = form.cleaned_data['city']
        gender = form.cleaned_data['gender']
        age_more_than = form.cleaned_data['age_more_than']
        age_less_than = form.cleaned_data['age_less_than']

        search_res = []
        target_fields = {"first_name", "last_name", "email", "phone", "university", "profession"}

        for item in response:
            if not key:
                search_res.append(item)
            else:
                match_found = False
                for title, field in item.items():
                    if title in target_fields:
                        if str(key).lower() in str(field).lower():
                            search_res.append(item)
                            match_found = True
                            break
                if match_found:
                    continue 
        
        if city:
            search_res = [item for item in search_res if item["city"] == city]

        if gender:
            search_res = [item for item in search_res if item["gender"] == gender]

        if age_more_than:
            search_res = [item for item in search_res if item["age"] > age_more_than]

        if age_less_than:
            search_res = [item for item in search_res if item["age"] < age_less_than]

        quantity = len(search_res)
        if quantity == 103:
            quantity = 0

        return render(request, 'candidates/index.html', {"response": search_res, "form": form, "quantity": quantity})


def reset(request):

    url = "http://127.0.0.1:8080/candidates/"
    form = SearchForm()

    response = requests.get(url).json()

    return render(request, 'candidates/index.html', {"response": response, "form": form})

templates/candidates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Hospital Staff Database</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" >
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="{% url 'staff:index' %}">Hospital Staff Database</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            </div>
        </nav>

        <header class="bg-primary bg-gradient text-white">
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">Hospital staff</h1>
            </div>
        </header>
        
        
        <br>
        <div style="margin: 30px 100px 5px 100px; text-align: center;">
            <form method="post" style="display: inline-block; vertical-align: top;">
                {% csrf_token %}
                {% for field in form %}
        
                {{ field.label_tag }}
                {{ field }}
        
        {% endfor %}
                <button type="submit" class="btn btn-secondary" style="vertical-align: top; margin-left: 35px;">Search</button>
            </form>
        </div>
        
        {% if quantity %}
        <div style="margin: 30px 250px 5px 280px; text-align: left;">
            <p><strong>The number of people that the search system found based on your search request – {{ quantity }}</strong></p>
        </div>
        {% endif %}
        
        <div style="display: flex; justify-content: center; margin: 20px 150px 40px 150px; padding: 20px 5px 40px 5px;">
            <table style="border-collapse: separate; border-spacing: 0; width: 100%; margin-top: 20px;">
                <thead style="background-color: lightgray;">
                    <tr>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">ID</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">First Name</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Last Name</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">City</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Email</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Phone</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Age</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Gender</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Education</th>
                        <th style="border-bottom: 1px solid rgba(128,128,128,0.5); padding: 12px;">Position</th>
                    </tr>
                </thead>
        
                <tbody>
                    {% for element in response %}
                    <tr>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.id}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.first_name}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.last_name}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.city}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.email}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.phone}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.age}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.gender}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.university}}</td>
                        <td style="border-bottom: 0.5px solid rgba(128,128,128,0.5); padding: 12px;">{{element.profession}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
            
        </div>
        
        <div style="margin: 20px auto; text-align: center;">

            <a href="{% url 'staff:index' %}" >
                <button class="btn btn-secondary">Reset</button>
            </a>

        </div>
        
        <br><br><br><br><br><br>
            
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; hospital-staff-database.de 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>